Repository MeilleursAgents/react-mapbox-wrapper, pull requests merged in 2018-09, with the labels that each got.

#2 Create LICENSE
  LICENSE
Labels: enhancement

#1 Adding 'fork on github', using flex for examples and package-lock
  README.md
  build/index.js
  examples/package-lock.json
  examples/package.json
  examples/public/index.html
  examples/src/App.css
  examples/src/App.jsx
  package-lock.json
  package.json
Labels: enhancement, front

#5 Adding default zoom and default export for mapbox
  .nycrc
  README.md
  build/index.js
  esdoc.json
  examples/src/AllInOne/index.jsx
  examples/src/App.css
  examples/src/App.jsx
  examples/src/CustomMarkerOnOver/index.jsx
  examples/src/MapWithMarker/index.jsx
  examples/src/MarkerWithPopup/index.jsx
  examples/src/SimpleMap/index.jsx
  examples/src/index.js
  src/Diagnose/index.js
  src/Helpers/index.js
  src/Lib/index.js
  src/MapboxMap/index.jsx
  src/MapboxMap/index.test.jsx
  src/Marker/index.jsx
  src/Marker/index.test.jsx
  src/Popup/index.jsx
  src/Popup/index.test.jsx
  src/index.js
Labels: doc, enhancement, front

#3 Sort API props
  README.md
Labels: doc
